# Generated by Django 3.2.6 on 2021-08-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('pair_address', models.CharField(
                    max_length=255, primary_key=True, serialize=False)),
                ('pair_name', models.CharField(max_length=255)),
                ('cmc_link', models.CharField(default='', max_length=255)),
                ('coin_gecko_link', models.CharField(default='', max_length=255)),
                ('telegram', models.CharField(default='', max_length=255)),
                ('website', models.CharField(default='', max_length=255)),
                ('twitter', models.CharField(default='', max_length=255)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
