# Generated by Django 3.2.6 on 2021-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='cmc_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='coin_gecko_link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='is_sponsored',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='is_trending',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
