# Generated by Django 3.2.6 on 2021-08-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_auto_20210816_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokens',
            old_name='pair_name',
            new_name='pair_base_name',
        ),
        migrations.AddField(
            model_name='tokens',
            name='pair_quote_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
