# Generated by Django 3.2.6 on 2021-08-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0004_auto_20210816_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokens',
            name='sponsored_details',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
