# Generated by Django 3.2.6 on 2021-09-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_tokens_sponsored_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaticTokens',
            fields=[
                ('pair_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pair_base_name', models.CharField(max_length=255)),
                ('pair_quote_name', models.CharField(default='', max_length=255)),
                ('pair_base_address', models.CharField(default='', max_length=255)),
                ('pair_quote_address', models.CharField(default='', max_length=255)),
                ('cmc_link', models.CharField(blank=True, default='', max_length=255)),
                ('coin_gecko_link', models.CharField(blank=True, default='', max_length=255)),
                ('telegram', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('twitter', models.CharField(blank=True, default='', max_length=255)),
                ('is_trending', models.BooleanField(blank=True, default=False)),
                ('is_sponsored', models.BooleanField(blank=True, default=False)),
                ('sponsored_details', models.CharField(blank=True, default='', max_length=500)),
                ('views', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PancakeTokens',
            fields=[
                ('pair_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pair_base_name', models.CharField(max_length=255)),
                ('pair_quote_name', models.CharField(default='', max_length=255)),
                ('pair_base_address', models.CharField(default='', max_length=255)),
                ('pair_quote_address', models.CharField(default='', max_length=255)),
                ('cmc_link', models.CharField(blank=True, default='', max_length=255)),
                ('coin_gecko_link', models.CharField(blank=True, default='', max_length=255)),
                ('telegram', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('twitter', models.CharField(blank=True, default='', max_length=255)),
                ('is_trending', models.BooleanField(blank=True, default=False)),
                ('is_sponsored', models.BooleanField(blank=True, default=False)),
                ('sponsored_details', models.CharField(blank=True, default='', max_length=500)),
                ('views', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UniswapTokens',
            fields=[
                ('pair_address', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pair_base_name', models.CharField(max_length=255)),
                ('pair_quote_name', models.CharField(default='', max_length=255)),
                ('pair_base_address', models.CharField(default='', max_length=255)),
                ('pair_quote_address', models.CharField(default='', max_length=255)),
                ('cmc_link', models.CharField(blank=True, default='', max_length=255)),
                ('coin_gecko_link', models.CharField(blank=True, default='', max_length=255)),
                ('telegram', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('twitter', models.CharField(blank=True, default='', max_length=255)),
                ('is_trending', models.BooleanField(blank=True, default=False)),
                ('is_sponsored', models.BooleanField(blank=True, default=False)),
                ('sponsored_details', models.CharField(blank=True, default='', max_length=500)),
                ('views', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
